- type: entity
  name: Stun baton
  parent: BaseItem
  id: Stunbaton
  components:
    - type: Sprite
      sprite: Objects/Melee/spear.rsi
      state: spear

    - type: Icon
      sprite: Objects/Melee/spear.rsi
      state: spear

    - type: Stunbaton
      range: 1.5
      arcwidth: 0
      arc: default

    - type: Item
      Size: 24
      sprite: Objects/Melee/spear.rsi
      prefix: inhand

    - type: ItemCooldown
