- type: entity
  name: stun baton
  parent: BaseItem
  id: Stunbaton
  components:
    - type: Sprite
      sprite: Objects/Melee/stunbaton.rsi
      state: stunbaton_off

    - type: Icon
      sprite: Objects/Melee/stunbaton.rsi
      state: stunbaton_off

    - type: Stunbaton
      damage: 1
      range: 0.75
      arcwidth: 0
      arc: default

    - type: Item
      Size: 10
      sprite: Objects/Melee/stunbaton.rsi
      HeldPrefix: off

    - type: ItemCooldown

- type: entity
  name: flash
  parent: BaseItem
  id: Flash
  components:
    - type: Sprite
      sprite: Objects/Melee/flash.rsi
      state: flash

    - type: Icon
      sprite: Objects/Melee/flash.rsi
      state: flash

    - type: Flash
      damage: 0
      cooldownTime: 1
      arc: smash
      hitSound: /Audio/weapons/flash.ogg
      slowTo: 0.7

    - type: Item
      Size: 2
      sprite: Objects/Melee/flash.rsi

    - type: ItemCooldown

