- type: job
  id: Chemist
  name: "chemist"
  startingGear: ChemistGear
  departments:
  - Medical
  icon: "Chemist"
  supervisors: "the chief medical officer"
  access:
  - Medical
  - Chemistry
  - Maintenance

- type: startingGear
  id: ChemistGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitChemistry
    back: ClothingBackpackChemistryFilled
    shoes: ClothingShoesColorWhite
    outerclothing: ClothingOuterCoatLabChem
    id: ChemistryPDA
    ears: ClothingHeadsetMedical
    belt: ClothingBeltMedical
    pocket1: HandLabeler
    # the purple glasses?
  innerclothingskirt: ClothingUniformJumpskirtChemistry
  satchel: ClothingBackpackSatchelChemistryFilled
  duffelbag: ClothingBackpackDuffelChemistryFilled
