# Best job.

- type: job
  id: ChiefMedicalOfficer
  name: "chief medical officer"
  head: true
  positions: 1
  startingGear: CMOGear
  departments:
  - Command
  - Medical
  icon: "ChiefMedicalOfficer"
  access:
  - Medical
  - ChiefMedicalOfficer
  - Command
  - Maintenance

- type: startingGear
  id: CMOGear
  equipment:
    innerclothing: ClothingUniformJumpsuitCMO
    backpack: ClothingBackpackMedicalFilled
    shoes: ClothingShoesColorBrown
    outerclothing: ClothingOuterCoatLabCmo
    idcard: CMOPDA
    ears: ClothingHeadsetAltMedical
    belt: ClothingBeltMedical
  innerclothingskirt: ClothingUniformJumpskirtCMO

