- type: job
  id: MedicalDoctor
  name: "medical doctor"
  startingGear: DoctorGear
  departments:
  - Medical
  icon: "MedicalDoctor"
  supervisors: "the chief medical officer"
  access:
  - Medical
  - Maintenance

- type: startingGear
  id: DoctorGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitMedicalDoctor
    back: ClothingBackpackMedicalFilled
    shoes: ClothingShoesColorWhite
    outerclothing: ClothingOuterCoatLab
    id: MedicalPDA
    ears: ClothingHeadsetMedical
    belt: ClothingBeltMedical
  innerclothingskirt: ClothingUniformJumpskirtMedicalDoctor
  satchel: ClothingBackpackSatchelMedicalFilled
  duffelbag: ClothingBackpackDuffelMedicalFilled
