- type: entity
  name: handcuff box
  parent: BoxBase
  id: BoxHandcuff
  description:
  components:
  - type: StorageFill
    contents:
      - name: Handcuffs
        amount: 6
  - type: Sprite
    layers:
      - state: box_security
      - state: handcuff

  - type: Item
  - type: Storage
    capacity: 6

- type: entity
  name: flashbang box
  parent: BoxBase
  id: BoxFlashbang
  description:
  components:
  - type: StorageFill
    contents:
      - name: GrenadeFlashBang
        amount: 4
  - type: Sprite
    layers:
      - state: box_security
      - state: flashbang

  - type: Item
  - type: Storage
    capacity: 20

- type: entity
  name: sechud box
  parent: BoxBase
  id: BoxSechud
  description:
  components:
  - type: StorageFill
    contents:
      - name: SecGlasses
        amount: 4
  - type: Sprite
    layers:
      - state: box_security
      - state: sechud

  - type: Item
  - type: Storage
    capacity: 20
