- type: entity
  name: handcuff box
  parent: BoxBase
  id: BoxHandcuff
  description: A box full of handcuffs.
  components:
  - type: StorageFill
    contents:
      - name: Handcuffs
        amount: 6
  - type: Sprite
    layers:
      - state: box_security
      - state: handcuff

  - type: Item
  - type: Storage
    capacity: 6

- type: entity
  name: flashbang box
  parent: BoxBase
  id: BoxFlashbang
  description: 'WARNING: These devices are extremely dangerous and can cause blindness or deafness in repeated use.'
  components:
  - type: StorageFill
    contents:
      - name: GrenadeFlashBang
        amount: 4
  - type: Sprite
    layers:
      - state: box_security
      - state: flashbang

  - type: Item
  - type: Storage
    capacity: 20

- type: entity
  name: sechud box
  parent: BoxBase
  id: BoxSechud
  description: A box of security glasses.
  components:
  - type: StorageFill
    contents:
      - name: SecGlasses
        amount: 4
  - type: Sprite
    layers:
      - state: box_security
      - state: sechud

  - type: Item
  - type: Storage
    capacity: 20
