- type: entity
  id: BaseSign
  name: base sign
  abstract: true
  components:
  - type: Clickable
  - type: InteractionOutline
  - type: Physics
    bodyType: Static
    canCollide: false
    fixtures:
    - shape:
        !type:PhysShapeAabb {}
  - type: Damageable
    damageContainer: Inorganic
    resistanceSet: Metallic
  - type: Destructible
    thresholds:
    - trigger:
        !type:DamageTrigger
        damage: 5
      behaviors:
      - !type:DoActsBehavior
        acts: ["Destruction"]
  - type: Sprite
    drawdepth: WallTops
    sprite: Structures/Wallmounts/signs.rsi
