- type: cargoProduct
  name: "Dice"
  id: cargo.dice
  description: Some dice
  icon:
    sprite: Objects/Fun/dice.rsi
    state: d2020
  product: d20
  cost: 20
  category: Other
  group: market

- type: cargoProduct
  name: "Medkit"
  id: cargo.Medkit
  description: Everything you need to patch someone up.
  icon: Objects/Medical/medkit_r.png
  product: Medkit
  cost: 200
  category: Medical
  group: market

- type: cargoProduct
  name: "Flashlight"
  id: cargo.flashlight
  description: Shine a light in the dark.
  icon:
    sprite: Objects/Tools/flashlight.rsi
    state: lantern_off
  product: crate_flashlight
  cost: 3000
  category: Engineering
  group: market

- type: cargoProduct
  name: "Light Bulb"
  id: cargo.lightbulb
  description: Light up a room, anywhere, anytime. Electricity not included.
  icon:
    sprite: Objects/Lighting/light_tube.rsi
    state: normal
  product: crate_light_bulb
  cost: 200
  category: Engineering
  group: market

- type: cargoProduct
  name: "Fire Extinguisher"
  id: cargo.fireextinguisher
  description: Puts out fires. Or propels you in space.
  icon: Objects/Misc/fire_extinguisher.png
  product: crate_fire_extinguisher
  cost: 300
  category: Other
  group: market

- type: cargoProduct
  name: "Pen"
  id: cargo.pen
  description: Expels ink. Use it to write, or stab someone.
  icon:
    sprite: Objects/Misc/bureaucracy.rsi
    state: pen
  product: crate_pen
  cost: 10
  category: Other
  group: market

- type: cargoProduct
  name: "Bike Horn"
  id: cargo.bikehorn
  description: HONK!
  icon:
    sprite: Objects/Fun/bikehorn.rsi
    state: icon
  product: crate_bikehorn
  cost: 300
  category: Other
  group: market

- type: cargoProduct
  name: "Cleaver"
  id: cargo.cleaver
  description: That's not a knife, THAT'S a knife.
  icon:
    sprite: Objects/Melee/cleaver.rsi
    state: butch
  product: crate_cleaver
  cost: 300
  category: Other
  group: blackmarket

- type: cargoProduct
  name: "Fuel Tank"
  id: cargo.fueltank
  description: Movable fuel tank for welders. No boom boom.
  icon: Buildings/weldtank.png
  product: crate_fueltank
  cost: 200
  category: Engineering
  group: market

- type: cargoProduct
  name: "Medical Scanner"
  id: cargo.medscanner
  description: Scans patients. First we stick this probe...
  icon:
    sprite: Buildings/medical_scanner.rsi
    state: scanner_open
  product: crate_medscanner
  cost: 400
  category: Medical
  group: market

- type: cargoProduct
  name: "Glass Crate"
  id: cargo.glass
  description: 50 sheets of glass.
  icon: Objects/Materials/sheet_glass.png
  product: crate_glass
  cost: 50
  category: Engineering
  group: market

- type: cargoProduct
  name: "Cable Crate"
  id: cargo.cable
  description: 50 coils of cable.
  icon: Objects/Tools/cable_coil.png
  product: crate_cable
  cost: 50
  category: Engineering
  group: market

