- type: MeleeWeaponAnimation
  id: default
  state: slash
  arcType: Slash
  length: 0.1
  color: 255,255,255,1020
  colorDelta: 0,0,0,-5100

- type: MeleeWeaponAnimation
  id: fist
  state: fist
  arcType: Poke
  length: 0.15
  speed: 1
