- type: entity
  id: BaseWindoor
  parent: BaseStructure
  abstract: true
  placement:
    mode: SnapgridCenter
  components:
  - type: InteractionOutline
  - type: Physics
    fixtures:
    - shape:
        !type:PhysShapeAabb
        bounds: "-0.2,-0.49,-0.49,0.49"
      mass: 50
      layer:
      - Impassable
      - MobImpassable
      - VaultImpassable
      - SmallImpassable
      mask:
      - VaultImpassable
  - type: Sprite
    netsync: false
    drawdepth: FloorObjects
    sprite: Structures/Doors/Windoors/glass.rsi
    layers:
    - state: closed
      map: [ "enum.DoorVisualLayers.Base" ]
    - state: closed_unlit
      shader: unshaded
      map: [ "enum.DoorVisualLayers.BaseUnlit" ]
    - state: welded
      map: [ "enum.DoorVisualLayers.BaseWelded" ]
    - state: bolted_unlit
      shader: unshaded
      map: [ "enum.DoorVisualLayers.BaseBolted" ]
    - state: panel_open
      map: [ "enum.WiresVisualLayers.MaintenancePanel" ]
  - type: ApcPowerReceiver
  - type: Damageable
    resistances: glassResistances
  - type: Destructible
    thresholds:
    - trigger:
        !type:DamageTrigger
        damage: 200
      behaviors:
      - !type:SpawnEntitiesBehavior
        spawn:
          ShardGlass:
            min: 1
            max: 2
      - !type:DoActsBehavior
        acts: [ "Destruction" ]
  - type: AccessReader
  - type: Airlock
  - type: Door
  - type: Wires
    BoardName: "Windoor Control"
    LayoutId: Airlock
  - type: UserInterface
    interfaces:
    - key: enum.WiresUiKey.Key
      type: WiresBoundUserInterface
  - type: Appearance
    visuals:
      - type: AirlockVisualizer
        open_sound: /Audio/Machines/windoor_open.ogg
        close_sound: /Audio/Machines/windoor_open.ogg
        deny_sound: /Audio/Machines/airlock_deny.ogg
        hasMaintenancePanel: false
        openCloseUnlit: false
        delay: 0.7

- type: entity
  id: BaseSecureWindoor
  parent: BaseWindoor
  abstract: true
  components:
  - type: Airtight
    fixVacuum: true
    noAirWhenFullyAirBlocked: false
    airBlockedDirection:
    - South
  - type: Sprite
    sprite: Structures/Doors/Windoors/secure.rsi
  - type: Destructible
    thresholds:
    - trigger:
        !type:DamageTrigger
        damage: 400
      behaviors:
      - !type:SpawnEntitiesBehavior
        spawn:
          ShardGlass:
            min: 1
            max: 2
      - !type:SpawnEntitiesBehavior
        spawn:
          MetalRod:
            min: 1
            max: 3
      - !type:DoActsBehavior
        acts: [ "Destruction" ]

# "0.49,-0.49,-0.49,-0.2"
# to:
# (-0.2, -0.49), (-0.2, 0.49), (-0.49, 0.49), (-0.49, -0.49)
# what i want is:
# (0.49, -0.49), (0.49, -0.2), (-0.49, -0.2), (-0.49, -0.49)
# which is:
# "-0.2,-0.49,-0.49,0.49"
