version: 1.0.{build}
image: Visual Studio 2017

before_build:
- cmd: py -3 -m pip install --user requests
- cmd: py -3 RUN_THIS.py --no-prompt
- cmd: nuget restore SpaceStation14.sln

build_script:
- ps: msbuild SpaceStation14.sln /v:m /m /nologo /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" /p:Platform=x64 /p:Configuration=Debug /p:AppVeyor=yes
