version: 1.0.{build}
image: Visual Studio 2019

platform: x64
configuration: Debug

build:
  project: SpaceStation.sln
  parallel: false
  verbosity: minimal

before_build:
- cmd: py -3 -m pip install --user requests
- cmd: py -3 RUN_THIS.py --no-prompt

build_script:
- ps: dotnet build SpaceStation14.sln /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" /p:AppVeyor=yes

test:
  assemblies:
    only:
    - bin/Content.IntegrationTests/Content.IntegrationTests.dll
    - bin/Content.Tests/Content.Tests.dll
