language: generic
dist: bionic
sudo: false

os:
- linux
#- osx

addons:
  apt:
    packages:
    - python3
    - python3-pip

cache:
  directories:
  - packages/
  - RobustToolbox/Dependencies/

install:
- curl -sSL https://dot.net/v1/dotnet-install.sh | bash /dev/stdin --version 3.1.100

#before_install:
#  - if [ $TRAVIS_OS_NAME = osx ]; then brew update && brew upgrade python; fi

before_script:
- "python3.6 -m pip install --user requests"
- "python3.6 RUN_THIS.py --no-prompt"

script:
- "Tools/run_travis.sh"


