language: csharp

dist: trusty
sudo: false

os:
- linux
#- osx

addons:
  apt:
    #sources:
    #- deadsnakes

    packages:
    - python3.5
    - python3-pip

cache:
  directories:
  - packages/
  - RobustToolbox/Dependencies/
  - RobustToolbox/SS14.Client.Godot/.mono/assemblies/

#before_install:
#  - if [ $TRAVIS_OS_NAME = osx ]; then brew update && brew upgrade python; fi

before_script:
#- "if [ $TRAVIS_OS_NAME = linux ]; then pyenv shell 3.6; fi"
- "python3.5 -m pip install --user requests"
- "nuget restore SpaceStation14Content.sln"
- "python3.5 RUN_THIS.py --no-prompt"
- "RobustToolbox/Tools/download_godotsharp.py"

script:
  # Prevent people from putting in textures/ (lowercase).
- "if [ -d Resources/textures ]; then exit 1; fi"
- "msbuild /p:Configuration=Debug /p:Platform=x64 /p:HEADLESS=1 /p:Configuratio=Debug /nologo /m /p:AllowMissingMacNatives=yes SpaceStation14Content.sln /p:Python=python3.5"


