language: csharp

dist: trusty
sudo: false
mono: none
# dotnet: 3.1.100 # Travis is shitting itself right now and it can't locate .NET Core packages.

os:
- linux
#- osx

addons:
  apt:
    #sources:
    #- deadsnakes

    packages:
    - python3.5
    - python3-pip

cache:
  directories:
  - packages/
  - RobustToolbox/Dependencies/

install:
- curl -sSL https://dot.net/v1/dotnet-install.sh | bash /dev/stdin --version 3.1.100

#before_install:
#  - if [ $TRAVIS_OS_NAME = osx ]; then brew update && brew upgrade python; fi

before_script:
#- "if [ $TRAVIS_OS_NAME = linux ]; then pyenv shell 3.6; fi"
- "python3.5 -m pip install --user requests"
- "python3.5 RUN_THIS.py --no-prompt"

script:
- "Tools/run_travis.sh"


