trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: Setup
  steps:
  - script: git submodule init --recursive --update
  - script: nuget restore SpaceStation14.sln

- job: Test
  steps:
  - script: msbuild SpaceStation14.sln /p:Configuration=Debug /p:Platform=x64 /nologo /m SpaceStation14.sln
  - script: mono packages/nunit.consolerunner/3.10.0/tools/nunit3-console.exe bin/Content.Tests/Content.Tests.dll bin/Content.IntegrationTests/Content.IntegrationTests.dll

- job: Package
  steps:
  - script: Tools/package_release_build.py -p windows mac linux
  - script: mv release/*.zip $(Build.ArtifactStagingDirectory)
  - task: PublishPipelineArtifact@1
    inputs:
      path: '$(Build.ArtifactStagingDirectory)'
      artifactName: 'Builds'
