status = [ "Build & Test Debug", "Build & Test Release", "Test Packaging", "YAML Linter", "YAML schema validator" ]
timeout_sec = 1800 # 30 minutes
use_squash_merge = true # Shame this can't use GH squash but what can you do
