- type: job
  id: CentralCommandOffical
  name: "centcom official"
  setPreference: false
  startingGear: CentcomGear
  departments:
    - Command
  icon: "Nanotrasen"
  supervisors: "the head of security"
  access:
  - Command
  - Maintenance

- type: startingGear
  id: CentcomGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitCentcomOfficial
    shoes: ClothingShoesBootsJack
    head: ClothingHeadHatCentcom
    eyes: ClothingEyesGlassesSunglasses
    gloves: ClothingHandsGlovesColorBlack
    outerClothing: ClothingOuterVestKevlar
    id: CentcomPDA
    ears: ClothingHeadsetAltCommand
    pocket1: Paper
    pocket2: Pen
