- type: job
  id: CentralCommandOffical
  name: "centcom official"
  startingGear: CentcomGear
  departments:
    - Command
  icon: "Nanotrasen"
  supervisors: "the head of security"
  access:
    - Command
    - Maintenence

- type: startingGear
  id: CentcomGear
  equipment:
    innerclothing: ClothingUniformJumpsuitCentcomOfficial
    shoes: ClothingShoesBootsJack
    head: ClothingHeadHatCentcom
    eyes: ClothingEyesGlassesSunglasses
    gloves: ClothingHandsGlovesColorBlack
    outerclothing: ClothingOuterVestKevlar
    idcard: CentcomPDA
    ears: ClothingHeadsetAltCommand
    pocket1: Paper
    pocket2: Pen
