- type: gameMapPool
  id: CorvaxDefaultMapPool
  maps:
  - CorvaxDelta
  - CorvaxAvrite
  - CorvaxSpectrum
  - CorvaxGate
  - CorvaxSilly
  - CorvaxOutpost
  - CorvaxAstra
  - CorvaxGelta
  - CorvaxMaus
  - Bagel
  - Box
  - Cluster
  - Core
  - Fland
  - Marathon
  - Meta
  - Omega
  - Origin
  - Saltern
  - Packed
