- type: job
  id: HeadOfSecurity
  name: "Head Of Security"
  head: true
  positions: 1
  startingGear: AssistantGear
  department:
  - Command
  - Security

  access:
  - command
  - security
  - maintenance
