# TODO: Add descriptions (3)

- type: entity
  id: AutolatheMachineCircuitboard
  parent: BaseMachineCircuitboard
  name: Autolathe (Machine Board)
  components:
    - type: MachineBoard
      prototype: Autolathe
      requirements:
        MatterBin: 3
        Manipulator: 1
      materialRequirements:
        Glass: 1

- type: entity
  id: ProtolatheMachineCircuitboard
  parent: BaseMachineCircuitboard
  name: Protolathe (Machine Board)
  components:
    - type: MachineBoard
      prototype: Protolathe
      requirements:
        MatterBin: 2
        Manipulator: 2
      tagRequirements:
        GlassBeaker:
          Amount: 2
          DefaultPrototype: Beaker
          ExamineName: Glass Beaker

- type: entity
  id: CloningPodMachineCircuitboard
  parent: BaseMachineCircuitboard
  name: Cloning Pod (Machine Board)
  components:
    - type: MachineBoard
      prototype: CloningPod
      requirements:
        ScanningModule: 2
        Manipulator: 2
      materialRequirements:
        Glass: 1
        Cable: 1

- type: entity
  id: MedicalScannerMachineCircuitboard
  parent: BaseMachineCircuitboard
  name: Medical Scanner (Machine Board)
  components:
    - type: MachineBoard
      prototype: MedicalScanner
      requirements:
        ScanningModule: 1
        Manipulator: 1
        Laser: 1
      materialRequirements:
        Glass: 1
        Cable: 1

- type: entity
  id: ChemMasterMachineCircuitboard
  parent: BaseMachineCircuitboard
  name: Chem Master (Machine Board)
  components:
    - type: MachineBoard
      prototype: chem_master
      requirements:
        Manipulator: 1
      materialRequirements:
        Glass: 1
      tagRequirements:
        GlassBeaker:
          Amount: 2
          DefaultPrototype: Beaker
          ExamineName: Glass Beaker

- type: entity
  id: ChemDispenserMachineCircuitboard
  parent: BaseMachineCircuitboard
  name: Chem Dispenser (Machine Board)
  components:
    - type: MachineBoard
      prototype: chem_dispenser
      requirements:
        Capacitor: 1
        Manipulator: 1
        MatterBin: 2
      materialRequirements:
        Glass: 1

- type: entity
  id: HydroponicsTrayMachineCircuitboard
  parent: BaseMachineCircuitboard
  name: Hydroponics Tray (Machine Board)
  components:
    - type: MachineBoard
      prototype: hydroponicsTray
      # See: https://github.com/vgstation-coders/vgstation13/blob/e9a806f30b4db0efa2a68b9eb42e3120d2321b6a/code/modules/hydroponics/hydro_tray.dm#L57
      requirements:
        MatterBin: 2
        ScanningModule: 1
        Capacitor: 1
      materialRequirements:
        # replacing the console screen
        Glass: 1
      tagRequirements:
        GlassBeaker:
          Amount: 2
          DefaultPrototype: Beaker
          ExamineName: Glass Beaker

- type: entity
  id: KitchenReagentGrinderMachineCircuitboard #unsure why the reagent grinder has 'kitchen' in the id name when multiple departments use it but that's for another time
  parent: BaseMachineCircuitboard
  name: Reagent Grinder (Machine Board)
  components:
    - type: MachineBoard
      prototype: KitchenReagentGrinder
      requirements:
        Laser: 1
        ScanningModule: 1
        MatterBin: 2
      tagRequirements:
        GlassBeaker:
          Amount: 1
          DefaultPrototype: Beaker
          ExamineName: Glass Beaker

