# TODO: Add descriptions (3)

- type: entity
  id: AutolatheMachineCircuitboard
  parent: BaseMachineCircuitboard
  name: Autolathe (Machine Board)
  components:
    - type: MachineBoard
      prototype: Autolathe
      requirements:
        MatterBin: 3
        Manipulator: 1
      materialRequirements:
        Glass: 1

- type: entity
  id: ProtolatheMachineCircuitboard
  parent: BaseMachineCircuitboard
  name: Protolathe (Machine Board)
  components:
    - type: MachineBoard
      prototype: Protolathe
      requirements:
        MatterBin: 2
        Manipulator: 2
      tagRequirements:
        GlassBeaker:
          Amount: 2
          DefaultPrototype: Beaker
          ExamineName: Glass Beaker

- type: entity
  id: CloningPodMachineCircuitboard
  parent: BaseMachineCircuitboard
  name: Cloning Pod (Machine Board)
  components:
    - type: MachineBoard
      prototype: CloningPod
      requirements:
        ScanningModule: 2
        Manipulator: 2
      materialRequirements:
        Glass: 1
        Cable: 1

- type: entity
  id: MedicalScannerMachineCircuitboard
  parent: BaseMachineCircuitboard
  name: Medical Scanner (Machine Board)
  components:
    - type: MachineBoard
      prototype: MedicalScanner
      requirements:
        ScanningModule: 1
        Manipulator: 1
        Laser: 1
      materialRequirements:
        Glass: 1
        Cable: 1
