- type: job
  id: HeadOfSecurity
  name: "head of security"
  head: true
  positions: 1
  startingGear: HoSGear
  department:
  - Command
  - Security
  icon: "HeadOfSecurity"
  access:
  - Command
  - Security
  - Maintenance
  - Service

- type: startingGear
  id: HoSGear
  equipment:
    innerclothing: UniformHoS
    backpack: SecPackFilled
    shoes: ShoesJackboots
    outerclothing: OuterclothingHoSTrenchcoat
    eyes: SecGlasses
    head: HatBeretHoS
    idcard: HoSPDA
    ears: HeadsetSecurityAlt
