- type: job
  id: HeadOfSecurity
  name: job-name-hos
  description: job-description-hos
  playTimeTracker: JobHeadOfSecurity
  requirements:
    - !type:RoleTimeRequirement
      role: JobWarden
      time: 36000 # Corvax-RoleTime
    - !type:DepartmentTimeRequirement
      department: Security
      time: 108000 # Corvax-RoleTime
#    - !type:OverallPlaytimeRequirement
#      time: 108000
  weight: 10
  startingGear: HoSGear
  icon: "HeadOfSecurity"
  requireAdminNotify: true
  supervisors: job-supervisors-captain
  canBeAntag: false
  access:
  - HeadOfSecurity
  - Command
  - Brig
  - Security
  - Armory
  - Maintenance
  - Service
  - External

- type: startingGear
  id: HoSGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitHoS
    back: ClothingBackpackHOSFilled
    shoes: ClothingShoesBootsJackSec # Corvax-Resprite
    outerClothing: ClothingOuterCoatHoSTrench
    eyes: ClothingEyesGlassesSecurity
    head: ClothingHeadHatBeretHoS
    id: HoSPDA
    gloves: ClothingHandsGlovesCombat
    ears: ClothingHeadsetAltSecurity
    belt: ClothingBeltSecurityFilled
  innerclothingskirt: ClothingUniformJumpskirtHoS
  satchel: ClothingBackpackSatchelHOSFilled
  duffelbag: ClothingBackpackDuffelHOSFilled
