- type: job
  id: HeadOfSecurity
  name: "head of security"
  head: true
  startingGear: HoSGear
  departments:
  - Command
  - Security
  icon: "HeadOfSecurity"
  requireAdminNotify: true
  supervisors: "the captain"
  canBeAntag: false
  access:
  - HeadOfSecurity
  - Command
#  - Brig
  - Security
  - Armory
  - Maintenance
  - Service

- type: startingGear
  id: HoSGear
  equipment:
    innerclothing: ClothingUniformJumpsuitHoS
    backpack: ClothingBackpackSecurityFilled
    shoes: ClothingShoesBootsJack
    outerclothing: ClothingOuterCoatHoSTrench
    eyes: ClothingEyesGlassesSecurity
    head: ClothingHeadHatBeretHoS
    idcard: HoSPDA
    ears: ClothingHeadsetAltSecurity
    belt: ClothingBeltSecurityFilled
  innerclothingskirt: ClothingUniformJumpskirtHoS
  satchel: ClothingBackpackSatchelSecurityFilled
  duffelbag: ClothingBackpackDuffelSecurityFilled
