- type: job
  id: SecurityOfficer
  name: "security officer"
  positions: 3
  spawnPositions: 2
  startingGear: SecurityOfficerGear
  departments:
  - Security
  icon: "SecurityOfficer"
  access:
  - Security
  - Maintenance
  - Service

- type: startingGear
  id: SecurityOfficerGear
  equipment:
    innerclothing: ClothingUniformJumpsuitSec
    backpack: ClothingBackpackSecurityFilled
    shoes: ClothingShoesBootsJack
    eyes: ClothingEyesGlassesSecurity
    head: ClothingHeadHelmetHelmetOld
    outerclothing: ClothingOuterVestKevlar
    idcard: SecurityPDA
    ears: ClothingHeadsetSecurity
    belt: ClothingBeltSecurityFilled
  innerclothingskirt: ClothingUniformJumpskirtSec

