- type: entity
  abstract: true
  parent: Clothing
  id: ClothingOuterBase
  components:
  - type: Clothing
    Slots:
    - outerclothing
  - type: Sprite
    state: icon

- type: entity
  abstract: true
  parent: ClothingOuterBase
  id: ClothingOuterHardsuitBase
  name: base hardsuit
  components:
  - type: PressureProtection
    highPressureMultiplier: 0.75
    lowPressureMultiplier: 100
  - type: Armor
    modifiers:
      coefficients:
        Blunt: 0.90
        Slash: 0.90
        Piercing: 0.95
        Heat: 0.90
        Radiation: 0.25
