[game]
hostname = "[RU][MRP][TTS] Corvax ☄️ Echo (ss14.ru)"
desc = "[Требуется 10 часов на другом сервере Corvax]\n[Имеется интеграция TTS (Text-To-Speech)]\nРусскоязычный сервер проекта Corvax со средним уровнем РП отыгрыша"
map_pool = "CorvaxDefaultMapPool"
maxplayers = 160
soft_max_players = 70
map_rotation = true

[game.panic_bunker]
enabled = true
show_reason = true
min_account_age = 0
min_overall_hours = 10

[rules]
time = 180.0

[queue]
enabled = true

[tts]
enabled = true

[discord_auth]
enabled = true

[hub]
advertise = true
tags = "lang:ru,rp:med,region:eu_e,tts"
