[game]
hostname = "[RU][MRP]{Новичкам} Corvax 🌑 Elysium (ss14.ru)"
desc = "[Помошь новичкам]\nРусскоязычный сервер проекта Corvax со сниженным уровнем РП отыгрыша"
map_pool = "CorvaxMapPool"
maxplayers = 180
soft_max_players = 100
map_rotation = false

[rules]
time = 10.0

[queue]
enabled = true

[tts]
enabled = false

[discord_auth]
enabled = true

[hub]
advertise = true
tags = "lang:ru,rp:med,region:eu_e,tts"
