- type: entity
  name: handcuff box
  parent: BoxCardboard
  id: BoxHandcuff
  description: A box full of handcuffs.
  components:
  - type: StorageFill
    contents:
      - id: Handcuffs
        amount: 6
  - type: Sprite
    layers:
      - state: box_security
      - state: handcuff

- type: entity
  name: flashbang box
  parent: BoxCardboard
  id: BoxFlashbang
  description: 'WARNING: These devices are extremely dangerous and can cause blindness or deafness in repeated use.'
  components:
  - type: StorageFill
    contents:
      - id: GrenadeFlashBang
        amount: 4
  - type: Sprite
    layers:
      - state: box_security
      - state: flashbang

- type: entity
  name: sechud box
  parent: BoxCardboard
  id: BoxSechud
  description: A box of security glasses.
  components:
  - type: StorageFill
    contents:
      - id: ClothingEyesGlassesSecurity
        amount: 4
  - type: Sprite
    layers:
      - state: box_security
      - state: sechud

- type: entity
  name: ziptie box
  parent: BoxCardboard
  id: BoxZiptie
  description: A box full of zipties.
  components:
  - type: StorageFill
    contents:
      - id: Zipties
        amount: 10
  - type: Sprite
    layers:
      - state: box_security
      - state: ziptie

- type: entity
  name: forensic pad box
  parent: BoxCardboard
  id: BoxForensicPad
  description: A box of forensic pads.
  components:
  - type: StorageFill
    contents:
      - id: ForensicPad
        amount: 10
  - type: Sprite
    layers:
      - state: box_security

# TODO: THESE ARE BAD AND ARE DEPRECATED, DON'T USE THEM PLEASE
- type: entity
  name: box of shotgun beanbag cartridges
  parent: BoxCardboard
  id: BoxBeanbag
  description: A box full of beanbag shots, designed for riot shotguns.
  components:
    - type: StorageFill
      contents:
        - id: ShellShotgunBeanbag
          amount: 6
    - type: Sprite
      layers:
        - state: boxwide
        - state: shellbeanbag

- type: entity
  name: box of shotgun lethal cartridges
  parent: BoxCardboard
  id: BoxLethalshot
  description: A box full of lethal pellet shots, designed for riot shotguns.
  components:
    - type: StorageFill
      contents:
        - id: ShellShotgun
          amount: 6
    - type: Sprite
      layers:
        - state: boxwide
        - state: shelllethal

- type: entity
  name: box of shotgun slug cartridges
  parent: BoxCardboard
  id: BoxShotgunSlug
  description: A box full of shotgun slugs, designed for riot shotguns.
  components:
    - type: StorageFill
      contents:
        - id: ShellShotgunSlug
          amount: 6
    - type: Sprite
      layers:
        - state: boxwide
        - state: shellslug

- type: entity
  name: box of shotgun flare cartridges
  parent: BoxCardboard
  id: BoxShotgunFlare
  description: A box full of shotgun flare cartridges, designed for riot shotguns.
  components:
    - type: StorageFill
      contents:
        - id: ShellShotgunFlare
          amount: 6
    - type: Sprite
      layers:
        - state: boxwide
        - state: shellflare

- type: entity
  name: box of shotgun incendiary cartridges
  parent: BoxCardboard
  id: BoxShotgunIncendiary
  description: A box full of shotgun incendiary cartridges, designed for riot shotguns.
  components:
    - type: StorageFill
      contents:
        - id: ShellShotgunIncendiary
          amount: 6
    - type: Sprite
      layers:
        - state: boxwide
        - state: shellincendiary

- type: entity
  name: box of shotgun practice cartridges
  parent: BoxCardboard
  id: BoxShotgunPractice
  description: A box full of shotgun practice cartridges, designed for riot shotguns.
  components:
    - type: StorageFill
      contents:
        - id: ShellShotgunPractice
          amount: 6
    - type: Sprite
      layers:
        - state: boxwide
        - state: shellpractice

- type: entity
  name: box of tranquilizer cartridges
  parent: BoxCardboard
  id: BoxShellTranquilizer
  description: A box full of tranquilizer cartridges, designed for riot shotguns.
  components:
    - type: StorageFill
      contents:
        - id: ShellTranquilizer
          amount: 6
    - type: Sprite
      layers:
        - state: boxwide
        - state: shellslug

# SRifle
- type: entity
  name: box of .20 rifle magazines
  parent: BoxCardboard
  id: BoxMagazineRifle
  description: A box full of .20 rifle magazines.
  components:
    - type: StorageFill
      contents:
        - id: MagazineRifle
          amount: 6

- type: entity
  name: box of .20 rifle (high-velocity) magazines
  parent: BoxCardboard
  id: BoxMagazineRifleHighVelocity
  description: A box full of .20 rifle (high-velocity) magazines.
  components:
    - type: StorageFill
      contents:
        - id: MagazineRifleHighVelocity
          amount: 6

- type: entity
  name: box of .20 rifle (practice) magazines
  parent: BoxCardboard
  id: BoxMagazineRiflePractice
  description: A box full of .20 rifle (practice) magazines.
  components:
    - type: StorageFill
      contents:
        - id: MagazineRiflePractice
          amount: 6

- type: entity
  name: box of .20 rifle (rubber) magazines
  parent: BoxCardboard
  id: BoxMagazineRifleRubber
  description: A box full of .20 rifle (rubber) magazines.
  components:
    - type: StorageFill
      contents:
        - id: MagazineRifleRubber
          amount: 6

- type: entity
  name: box of .30 rifle bullets
  parent: BoxCardboard
  id: BoxBulletLightRifleSmall
  description: A box full of individual .30 rifle bullets.
  components:
    - type: StorageFill
      contents:
        - id: CartridgeLightRifle
          amount: 20
