using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._c4llv07e.Sponsors;

[GenerateTypedNameReferences]
public sealed partial class PatronCategoryNotAvailable : Control
{
    [Dependency] private readonly IUriOpener _uri = default!;

    public PatronCategoryNotAvailable()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        Boosty.OnPressed += _ => _uri.OpenUri("https://boosty.to/darkeneez"); //TODO BY UR
    }
}
