name: "Сообщить о проблеме"
description: "Если что-то работает не так, как ожидалось"
labels: ["triage"]
body:
  - type: textarea
    validations:
      required: true
    attributes:
      label: "Описание"
      description: "Опишите проблему как можно подробнее"

  - type: textarea
    attributes:
      label: "Шаги воспроизведения"
      description: "Если применимо, опишите шаги для воспроизведения проблемы"
      placeholder: |
        1. Открывать интерфейс консоли
        2. Нажать кнопку "Старт"
        3. Получить ошибку...

  - type: textarea
    attributes:
      label: "Скриншоты"
      description: |
        Если применимо, добавьте скриншоты, чтобы помочь объяснить вашу проблему
        **Подсказка**: Вы можете прикрепить изображения, щелкнув по этой области, чтобы выделить ее, а затем перетащив в нее файлы
