- type: job
  id: ChiefEngineer
  name: "chief engineer"
  head: true
  startingGear: ChiefEngineerGear
  departments:
  - Command
  - Engineering
  icon: "ChiefEngineer"
  requireAdminNotify: true
  supervisors: "the captain"
  canBeAntag: false
  access:
  - Maintenance
  - Engineering
  - Command
  - External

- type: startingGear
  id: ChiefEngineerGear
  equipment:
    head: ClothingHeadHatHardhatWhite
    innerclothing: ClothingUniformJumpsuitChiefEngineer
    backpack: ClothingBackpackEngineeringFilled
    shoes: ClothingShoesColorBrown
    idcard: CEPDA
    ears: ClothingHeadsetEngineering
    belt: ClothingBeltChiefEngineerFilled
  innerclothingskirt: ClothingUniformJumpskirtChiefEngineer
  satchel: ClothingBackpackSatchelEngineeringFilled
  duffelbag: ClothingBackpackDuffelEngineeringFilled
