- type: job
  id: ChiefEngineer
  name: "chief engineer"
  head: true
  startingGear: ChiefEngineerGear
  departments:
  - Command
  - Engineering
  icon: "ChiefEngineer"
  requireAdminNotify: true
  supervisors: "the captain"
  canBeAntag: false
  access:
  - Maintenance
  - Engineering
  - Command
  - External
  - ChiefEngineer

- type: startingGear
  id: ChiefEngineerGear
  equipment:
    head: ClothingHeadHatHardhatWhite
    jumpsuit: ClothingUniformJumpsuitChiefEngineer
    back: ClothingBackpackEngineeringFilled
    shoes: ClothingShoesColorBrown
    id: CEPDA
    ears: ClothingHeadsetEngineering
    belt: ClothingBeltChiefEngineerFilled
  innerclothingskirt: ClothingUniformJumpskirtChiefEngineer
  satchel: ClothingBackpackSatchelEngineeringFilled
  duffelbag: ClothingBackpackDuffelEngineeringFilled
