- type: job
  id: ChiefEngineer
  name: "chief engineer"
  head: true
  positions: 1
  startingGear: ChiefEngineerGear
  department:
  - Command
  - Engineering
  icon: "ChiefEngineer"
  access:
  - Maintenance
  - Engineering
  - Command
  - External

- type: startingGear
  id: ChiefEngineerGear
  equipment:
    head: HatHardhatWhite
    innerclothing: UniformChiefEngineer
    backpack: BackpackEngineeringFilled
    shoes: ShoesBrown
    idcard: CEPDA
    belt: UtilityBeltClothingFilled
