- type: job
  id: StationEngineer
  name: "station engineer"
  positions: 3
  spawnPositions: 2
  startingGear: StationEngineerGear
  departments:
  - Engineering
  icon: "StationEngineer"
  access:
  - Maintenance
  - Engineering
  - External

- type: startingGear
  id: StationEngineerGear
  equipment:
    head: ClothingHeadHatHardhatYellow
    innerclothing: ClothingUniformJumpsuitEngineering
    backpack: ClothingBackpackEngineeringFilled
    shoes: ClothingShoesBootsWork
    outerclothing: ClothingOuterVestHazard
    idcard: EngineerPDA
    belt: ClothingBeltUtilityFilled
    ears: ClothingHeadsetEngineering
