- type: job
  id: StationEngineer
  name: "station engineer"
  startingGear: StationEngineerGear
  departments:
  - Engineering
  icon: "StationEngineer"
  supervisors: "the chief engineer"
  access:
  - Maintenance
  - Engineering
  - External

- type: startingGear
  id: StationEngineerGear
  equipment:
    head: ClothingHeadHatHardhatYellow
    jumpsuit: ClothingUniformJumpsuitEngineering
    back: ClothingBackpackEngineeringFilled
    shoes: ClothingShoesBootsWork
    outerclothing: ClothingOuterVestHazard
    id: EngineerPDA
    belt: ClothingBeltUtilityFilled
    ears: ClothingHeadsetEngineering
  innerclothingskirt: ClothingUniformJumpskirtEngineering
  satchel: ClothingBackpackSatchelEngineeringFilled
  duffelbag: ClothingBackpackDuffelEngineeringFilled
