# HoS
- type: entity
  id: LockerHeadOfSecurity
  parent: LockerSecureBase
  name: "head of security's locker"
  components:
  - type: Appearance
    visuals:
    - type: StorageVisualizer
      state: hos
  - type: AccessReader
    access: [["HeadOfSecurity"]]

# Warden
- type: entity
  id: LockerWarden
  parent: LockerSecureBase
  name: "warden's locker"
  components:
  - type: Appearance
    visuals:
    - type: StorageVisualizer
      state: warden
  - type: AccessReader
    access: [["Brig"]]

# Security Officer
- type: entity
  id: LockerSecurity
  parent: LockerSecureBase
  name: "security officer's locker"
  components:
  - type: Appearance
    visuals:
    - type: StorageVisualizer
      state: sec
  - type: AccessReader
    access: [["Security"]]

# Detective
- type: entity
  id: LockerDetective
  parent: LockerSecureBase
  name: "detective's cabinet"
  components:
  - type: Appearance
    visuals:
    - type: StorageVisualizer
      state: cabinet
  - type: AccessReader
    access: [["Detective"]]
