- type: latheRecipe
  id: Handcuffs
  icon:
    sprite: Objects/Misc/handcuffs.rsi
    state: handcuff
  result: Handcuffs
  completetime: 500
  materials:
    Steel: 300

- type: latheRecipe
  id: Stunbaton
  icon:
    sprite: Objects/Weapons/Melee/stunbaton.rsi
    state: stunbaton_off
  result: Stunbaton
  completetime: 500
  materials:
    Steel: 300
    Plastic: 300

- type: latheRecipe
  id: Flash
  icon:
    sprite: Objects/Weapons/Melee/flash.rsi
    state: flash
  result: Flash
  completetime: 500
  materials:
    Glass: 100
    Plastic: 200
    Steel: 100

- type: latheRecipe
  id: ShellShotgunBeanbag
  icon:
    sprite: Objects/Weapons/Guns/Ammunition/Casings/shotgun_shell_beanbag.rsi
    state: base
  result: ShellShotgunBeanbag
  completetime: 500
  materials:
    Plastic: 15
    Steel: 10
    
- type: latheRecipe
  id: CartridgePistolRubber
  icon:
    sprite: Objects/Weapons/Guns/Ammunition/Casings/ammo_casing.rsi
    state: base
  result: CartridgePistolRubber
  completetime: 500
  materials:
    Plastic: 5
    Steel: 5
    
- type: latheRecipe
  id: CartridgeMagnumRubber
  icon:
    sprite: Objects/Weapons/Guns/Ammunition/Casings/ammo_casing.rsi
    state: base
  result: CartridgeMagnumRubber
  completetime: 500
  materials:
    Plastic: 5
    Steel: 5
    
- type: latheRecipe
  id: CartridgeClRifleRubber
  icon:
    sprite: Objects/Weapons/Guns/Ammunition/Casings/ammo_casing.rsi
    state: base
  result: CartridgeClRifleRubber
  completetime: 500
  materials:
    Plastic: 10
    Steel: 5
    
- type: latheRecipe
  id: CartridgeLRifleRubber
  icon:
    sprite: Objects/Weapons/Guns/Ammunition/Casings/ammo_casing.rsi
    state: base
  result: CartridgeLRifleRubber
  completetime: 500
  materials:
    Plastic: 10
    Steel: 5
    
- type: latheRecipe
  id: CartridgeSRifleRubber
  icon:
    sprite: Objects/Weapons/Guns/Ammunition/Casings/ammo_casing.rsi
    state: base
  result: CartridgeSRifleRubber
  completetime: 500
  materials:
    Plastic: 10
    Steel: 5

- type: latheRecipe
  id: CartridgePistol
  icon:
    sprite: Objects/Weapons/Guns/Ammunition/Casings/ammo_casing.rsi
    state: base
  result: CartridgePistol
  completetime: 500
  materials:
    Steel: 10

- type: latheRecipe
  id: ShellShotgun
  icon:
    sprite: Objects/Weapons/Guns/Ammunition/Casings/shotgun_shell.rsi
    state: base
  result: ShellShotgun
  completetime: 500
  materials:
    Steel: 20

- type: latheRecipe
  id: CartridgeMagnum
  icon:
    sprite: Objects/Weapons/Guns/Ammunition/Casings/ammo_casing.rsi
    state: base
  result: CartridgeMagnum
  completetime: 500
  materials:
    Steel: 20

- type: latheRecipe
  id: CartridgeLRifle
  icon:
    sprite: Objects/Weapons/Guns/Ammunition/Casings/ammo_casing.rsi
    state: base
  result: CartridgeLRifle
  completetime: 500
  materials:
    Steel: 30
