- type: latheRecipe
  id: Handcuffs
  icon:
    sprite: Objects/Misc/handcuffs.rsi
    state: handcuff
  result: Handcuffs
  completetime: 500
  materials:
    Steel: 300

- type: latheRecipe
  id: Stunbaton
  icon:
    sprite: Objects/Weapons/Melee/stunbaton.rsi
    state: stunbaton_off
  result: Stunbaton
  completetime: 500
  materials:
    Steel: 300
    Plastic: 300

- type: latheRecipe
  id: Flash
  icon:
    sprite: Objects/Weapons/Melee/flash.rsi
    state: flash
  result: Flash
  completetime: 500
  materials:
    Glass: 100
    Plastic: 200
    Steel: 100

- type: latheRecipe
  id: CartridgePistolBase
  icon:
    sprite: Objects/Weapons/Guns/Ammunition/Casings/ammo_casing.rsi
    state: base
  result: CartridgePistolBase
  completetime: 500
  materials:
    Steel: 10

- type: latheRecipe
  id: ShellShotgunBase
  icon:
    sprite: Objects/Weapons/Guns/Ammunition/Casings/shotgun_shell.rsi
    state: base
  result: ShellShotgunBase
  completetime: 500
  materials:
    Steel: 20

- type: latheRecipe
  id: CartridgeMagnumBase
  icon:
    sprite: Objects/Weapons/Guns/Ammunition/Casings/ammo_casing.rsi
    state: base
  result: CartridgeMagnumBase
  completetime: 500
  materials:
    Steel: 20

- type: latheRecipe
  id: CartridgeLRifleBase
  icon:
    sprite: Objects/Weapons/Guns/Ammunition/Casings/ammo_casing.rsi
    state: base
  result: CartridgeLRifleBase
  completetime: 500
  materials:
    Steel: 30
