- type: gameMapPool
  id: DefaultMapPool
  maps:
  - Bagel
  - Box
  - Cluster
  - Kettle
  - Lighthouse
  - Marathon
  - Omega
  - Origin
  - Pillar
  - Saltern

- type: gameMapPool
  id: CorvaxMapPool
  maps:
    - Delta
    - Box
