#Misc outfit startingGear definitions.

#IHS Void Suit Outfit
- type: startingGear
  id: IHSGear
  equipment:
    innerclothing: ClothingUniformJumpsuitColorBlack
    backpack: ClothingBackpackFilled
    head: ClothingHeadHelmetIHSVoidHelm
    gloves: ClothingHandsGlovesIhscombat
    outerClothing: IHSVoidsuit
    shoes: ClothingShoesBootsJack
    idcard: AssistantPDA
    ears: ClothingHeadsetService
  innerclothingskirt: ClothingUniformJumpskirtColorBlack
  satchel: ClothingBackpackSatchelFilled
  duffelbag: ClothingBackpackDuffelFilled

#Pirate Outfit
- type: startingGear
  id: PirateGear
  equipment:
    innerclothing: ClothingUniformJumpsuitColorLightBrown
    backpack: ClothingBackpackSatchelEngineering
    head: ClothingHeadHatPirate
    outerClothing: ClothingOuterCoatPirate
    shoes: ClothingShoesBootsWork
    idcard: AssistantPDA
    belt: ClothingBeltUtility
  innerclothingskirt: ClothingUniformJumpskirtColorLightBrown
  satchel: ClothingBackpackSatchelEngineering
  duffelbag: ClothingBackpackSatchelEngineering

#Space Ninja Outfit
- type: startingGear
  id: SpaceNinjaGear
  equipment:
    innerclothing: ClothingUniformJumpsuitColorBlack
    backpack: ClothingBackpackFilled
    head: ClothingHeadHelmetSpaceNinja
    gloves: ClothingHandsGlovesSpaceNinja
    outerClothing: ClothingOuterSuitSpaceninja
    shoes: ClothingShoesSpaceNinja
    idcard: AssistantPDA
  innerclothingskirt: ClothingUniformJumpskirtColorBlack
  satchel: ClothingBackpackSatchelFilled
  duffelbag: ClothingBackpackDuffelFilled

#Deathsquad Outfit
- type: startingGear
  id: DeadsquadGear
  equipment:
    innerclothing: ClothingUniformJumpsuitColorBlack
    backpack: ClothingBackpackDuffelSyndicateAmmo
    head: ClothingHeadHelmetHardsuitDeathsquad
    mask: ClothingMaskBreath
    eyes: ClothingEyesGlassesSecurity
    ears: ClothingHeadsetCentCom
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterHardsuitDeathsquad
    shoes: ClothingShoesChameleonNoSlips
    idcard: CentcomPDA
    pocket1: EmergencyOxygenTankFilled
    belt: ClothingBeltUtilityFilled
  innerclothingskirt: ClothingUniformJumpskirtColorBlack
  satchel: ClothingBackpackDuffelSyndicateAmmo
  duffelbag: ClothingBackpackDuffelSyndicateAmmo
