- type: job
  id: CargoTechnician
  name: "cargo technician"
  positions: 2
  spawnPositions: 1
  startingGear: CargoTechGear
  departments:
  - Cargo
  icon: "CargoTechnician"
  supervisors: "the head of personnel" # TODO: Change this to include the QM when it gets in.
  access:
  - Cargo
  - Maintenance

- type: startingGear
  id: CargoTechGear
  equipment:
    head: ClothingHeadHatCargosoft
    innerclothing: ClothingUniformJumpsuitCargo
    backpack: ClothingBackpackFilled
    shoes: ClothingShoesColorBlack
    idcard: CargoPDA
    ears: ClothingHeadsetCargo
  innerclothingskirt: ClothingUniformJumpskirtCargo
  satchel: ClothingBackpackSatchelFilled
  duffelbag: ClothingBackpackDuffelFilled
