- type: job
  id: CargoTechnician
  name: "cargo technician"
  positions: 2
  spawnPositions: 1
  startingGear: CargoTechGear
  departments:
  - Cargo
  icon: "CargoTechnician"
  access:
  - Cargo
  - Maintenance

- type: startingGear
  id: CargoTechGear
  equipment:
    head: ClothingHeadHatCargosoft
    innerclothing: ClothingUniformJumpsuitCargo
    backpack: ClothingBackpackFilled
    shoes: ClothingShoesColorBlack
    idcard: CargoPDA
    ears: ClothingHeadsetCargo
