- type: entity
  abstract: true
  parent: Clothing
  id: ClothingUniformBase
  components:
  - type: Sprite
    state: icon
  - type: Clothing
    Slots: [innerclothing]
    EquipSound:
      path: /Audio/Items/jumpsuit_equip.ogg

- type: entity
  abstract: true
  parent: Clothing
  id: ClothingUniformSkirtBase
  components:
  - type: Sprite
    state: icon
  - type: Clothing
    Slots: [innerclothing]
    femaleMask: UniformTop
    EquipSound:
      path: /Audio/Items/jumpsuit_equip.ogg
