meta:
  format: 3
  name: DemoStation
  author: Space-Wizards
  postmapinit: false
tilemap:
  0: Space
  65: FloorShuttleWhite
  93: Lattice
  94: Plating
entities:
- uid: 0
  components:
  - type: MetaData
  - pos: -2.46875,-1.421875
    parent: invalid
    type: Transform
  - chunks:
      0,0:
        ind: 0,0
        tiles: XgAAAEEAAABBAAAAQQAAAF4AAABdAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAF4AAABBAAAAQQAAAEEAAABeAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABeAAAAQQAAAEEAAABBAAAAXgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAXgAAAEEAAABBAAAAQQAAAF4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAF4AAABeAAAAQQAAAF4AAABeAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAXgAAAF4AAABeAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==
      0,-1:
        ind: 0,-1
        tiles: AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAXQAAAF4AAABBAAAAXgAAAF0AAABdAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==
      -1,0:
        ind: -1,0
        tiles: AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAXQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==
      -1,-1:
        ind: -1,-1
        tiles: AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAXQAAAA==
    type: MapGrid
  - type: Broadphase
  - angularDamping: 0.05
    linearDamping: 0.05
    fixedRotation: False
    bodyType: Dynamic
    type: Physics
  - fixtures: []
    type: Fixtures
  - type: OccluderTree
  - type: Shuttle
  - nextUpdate: 1010.7455142
    type: GridPathfinding
  - gravityShakeSound: !type:SoundPathSpecifier
      path: /Audio/Effects/alert.ogg
    type: Gravity
  - chunkCollection:
      version: 2
      nodes: []
    type: DecalGrid
  - version: 2
    data:
      tiles:
        0,0:
          0: 13111
      uniqueMixes:
      - volume: 2500
        temperature: 293.15
        moles:
        - 21.824879
        - 82.10312
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
      chunkSize: 4
    type: GridAtmosphere
  - type: GasTileOverlay
  - type: RadiationGridResistance
- uid: 1
  type: WallShuttleDiagonal
  components:
  - rot: 1.5707963267948966 rad
    pos: 0.5,-0.5
    parent: 0
    type: Transform
- uid: 2
  type: WallShuttleDiagonal
  components:
  - rot: 3.141592653589793 rad
    pos: 4.5,-0.5
    parent: 0
    type: Transform
- uid: 3
  type: Grille
  components:
  - pos: 0.5,4.5
    parent: 0
    type: Transform
- uid: 4
  type: Grille
  components:
  - pos: 3.5,5.5
    parent: 0
    type: Transform
- uid: 5
  type: ShuttleWindow
  components:
  - pos: 1.5,5.5
    parent: 0
    type: Transform
- uid: 6
  type: Grille
  components:
  - pos: 3.5,4.5
    parent: 0
    type: Transform
- uid: 7
  type: WallShuttle
  components:
  - rot: 3.141592653589793 rad
    pos: 4.5,2.5
    parent: 0
    type: Transform
- uid: 8
  type: WallShuttle
  components:
  - rot: 3.141592653589793 rad
    pos: 4.5,1.5
    parent: 0
    type: Transform
- uid: 9
  type: ShuttleWindow
  components:
  - pos: 0.5,4.5
    parent: 0
    type: Transform
- uid: 10
  type: Grille
  components:
  - pos: 2.5,5.5
    parent: 0
    type: Transform
- uid: 11
  type: Grille
  components:
  - pos: 1.5,4.5
    parent: 0
    type: Transform
- uid: 12
  type: WallShuttleDiagonal
  components:
  - pos: -0.5,0.5
    parent: 0
    type: Transform
- uid: 13
  type: WallShuttleDiagonal
  components:
  - rot: -1.5707963267948966 rad
    pos: 5.5,0.5
    parent: 0
    type: Transform
- uid: 14
  type: WallShuttle
  components:
  - rot: -1.5707963267948966 rad
    pos: 0.5,0.5
    parent: 0
    type: Transform
- uid: 15
  type: WallShuttle
  components:
  - rot: -1.5707963267948966 rad
    pos: 0.5,3.5
    parent: 0
    type: Transform
- uid: 16
  type: WallShuttle
  components:
  - rot: -1.5707963267948966 rad
    pos: 4.5,3.5
    parent: 0
    type: Transform
- uid: 17
  type: WallShuttle
  components:
  - rot: -1.5707963267948966 rad
    pos: 4.5,0.5
    parent: 0
    type: Transform
- uid: 18
  type: WallShuttle
  components:
  - rot: -1.5707963267948966 rad
    pos: 3.5,-0.5
    parent: 0
    type: Transform
- uid: 19
  type: WallShuttle
  components:
  - rot: -1.5707963267948966 rad
    pos: 1.5,-0.5
    parent: 0
    type: Transform
- uid: 20
  type: Thruster
  components:
  - rot: 3.141592653589793 rad
    pos: -0.5,-0.5
    parent: 0
    type: Transform
  - bodyType: Static
    type: Physics
- uid: 21
  type: AirlockGlassShuttle
  components:
  - pos: 2.5,-0.5
    parent: 0
    type: Transform
  - fixtures:
    - shape: !type:PolygonShape
        radius: 0.01
        vertices:
        - 0.49,-0.49
        - 0.49,0.49
        - -0.49,0.49
        - -0.49,-0.49
      mask:
      - Impassable
      - MidImpassable
      - HighImpassable
      - LowImpassable
      - InteractImpassable
      layer:
      - MidImpassable
      - HighImpassable
      - BulletImpassable
      - InteractImpassable
      - Opaque
      density: 100
      hard: True
      restitution: 0
      friction: 0.4
      id: null
    - shape: !type:PhysShapeCircle
        radius: 0.2
        position: 0,-0.5
      mask: []
      layer: []
      density: 1
      hard: False
      restitution: 0
      friction: 0.4
      id: docking
    type: Fixtures
- uid: 22
  type: WallShuttle
  components:
  - rot: 3.141592653589793 rad
    pos: 0.5,2.5
    parent: 0
    type: Transform
- uid: 23
  type: WallShuttle
  components:
  - rot: 3.141592653589793 rad
    pos: 0.5,1.5
    parent: 0
    type: Transform
- uid: 24
  type: Grille
  components:
  - pos: 4.5,4.5
    parent: 0
    type: Transform
- uid: 25
  type: ShuttleWindow
  components:
  - pos: 2.5,5.5
    parent: 0
    type: Transform
- uid: 26
  type: Grille
  components:
  - pos: 1.5,5.5
    parent: 0
    type: Transform
- uid: 27
  type: ShuttleWindow
  components:
  - pos: 1.5,4.5
    parent: 0
    type: Transform
- uid: 28
  type: Thruster
  components:
  - rot: 3.141592653589793 rad
    pos: 5.5,-0.5
    parent: 0
    type: Transform
  - bodyType: Static
    type: Physics
- uid: 29
  type: TableReinforcedGlass
  components:
  - rot: -1.5707963267948966 rad
    pos: 3.5,0.5
    parent: 0
    type: Transform
- uid: 30
  type: ChairPilotSeat
  components:
  - rot: 1.5707963267948966 rad
    pos: 1.5,1.5
    parent: 0
    type: Transform
  - bodyType: Static
    type: Physics
- uid: 31
  type: ChairPilotSeat
  components:
  - rot: 1.5707963267948966 rad
    pos: 1.5,2.5
    parent: 0
    type: Transform
  - bodyType: Static
    type: Physics
- uid: 32
  type: ChairPilotSeat
  components:
  - rot: -1.5707963267948966 rad
    pos: 3.5,2.5
    parent: 0
    type: Transform
  - bodyType: Static
    type: Physics
- uid: 33
  type: ChairPilotSeat
  components:
  - rot: -1.5707963267948966 rad
    pos: 3.5,1.5
    parent: 0
    type: Transform
  - bodyType: Static
    type: Physics
- uid: 34
  type: TableReinforcedGlass
  components:
  - rot: -1.5707963267948966 rad
    pos: 1.5,0.5
    parent: 0
    type: Transform
- uid: 35
  type: ShuttleWindow
  components:
  - pos: 3.5,4.5
    parent: 0
    type: Transform
- uid: 36
  type: ShuttleWindow
  components:
  - pos: 3.5,5.5
    parent: 0
    type: Transform
- uid: 37
  type: ShuttleWindow
  components:
  - pos: 4.5,4.5
    parent: 0
    type: Transform
- uid: 38
  type: ClosetEmergencyFilledRandom
  components:
  - pos: 1.5,3.5
    parent: 0
    type: Transform
  - air:
      volume: 200
      immutable: False
      temperature: 147.92499
      moles:
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
    type: EntityStorage
- uid: 39
  type: ClosetFireFilled
  components:
  - pos: 3.5,3.5
    parent: 0
    type: Transform
- uid: 40
  type: EmergencyLight
  components:
  - rot: -1.5707963267948966 rad
    pos: 3.5,0.5
    parent: 0
    type: Transform
  - enabled: True
    type: PointLight
  - enabled: True
    type: AmbientSound
  - type: ActiveEmergencyLight
- uid: 41
  type: ToolboxEmergencyFilled
  components:
  - pos: 1.515625,0.6490259
    parent: 0
    type: Transform
- uid: 42
  type: DonkpocketBoxSpawner
  components:
  - pos: 3.5,0.5
    parent: 0
    type: Transform
- uid: 43
  type: CableHV
  components:
  - pos: 0.5,0.5
    parent: 0
    type: Transform
  - enabled: True
    type: AmbientSound
- uid: 44
  type: CableHV
  components:
  - pos: 1.5,0.5
    parent: 0
    type: Transform
- uid: 45
  type: CableHV
  components:
  - pos: 2.5,0.5
    parent: 0
    type: Transform
- uid: 46
  type: CableHV
  components:
  - pos: 2.5,1.5
    parent: 0
    type: Transform
- uid: 47
  type: CableHV
  components:
  - pos: 2.5,2.5
    parent: 0
    type: Transform
- uid: 48
  type: CableHV
  components:
  - pos: 2.5,3.5
    parent: 0
    type: Transform
- uid: 49
  type: CableHV
  components:
  - pos: 1.5,3.5
    parent: 0
    type: Transform
- uid: 50
  type: CableHV
  components:
  - pos: 0.5,3.5
    parent: 0
    type: Transform
  - enabled: True
    type: AmbientSound
- uid: 51
  type: CableMV
  components:
  - pos: 0.5,3.5
    parent: 0
    type: Transform
  - enabled: True
    type: AmbientSound
- uid: 52
  type: CableMV
  components:
  - pos: 1.5,3.5
    parent: 0
    type: Transform
- uid: 53
  type: CableMV
  components:
  - pos: 2.5,3.5
    parent: 0
    type: Transform
- uid: 54
  type: CableMV
  components:
  - pos: 2.5,2.5
    parent: 0
    type: Transform
- uid: 55
  type: CableMV
  components:
  - pos: 2.5,1.5
    parent: 0
    type: Transform
- uid: 56
  type: CableMV
  components:
  - pos: 2.5,0.5
    parent: 0
    type: Transform
- uid: 57
  type: CableMV
  components:
  - pos: 3.5,0.5
    parent: 0
    type: Transform
- uid: 58
  type: CableMV
  components:
  - pos: 4.5,0.5
    parent: 0
    type: Transform
  - enabled: True
    type: AmbientSound
- uid: 59
  type: CableApcExtension
  components:
  - pos: 4.5,0.5
    parent: 0
    type: Transform
  - enabled: True
    type: AmbientSound
- uid: 60
  type: CableApcExtension
  components:
  - pos: 3.5,0.5
    parent: 0
    type: Transform
- uid: 61
  type: CableApcExtension
  components:
  - pos: 2.5,0.5
    parent: 0
    type: Transform
- uid: 62
  type: CableApcExtension
  components:
  - pos: 2.5,1.5
    parent: 0
    type: Transform
- uid: 63
  type: CableApcExtension
  components:
  - pos: 2.5,2.5
    parent: 0
    type: Transform
- uid: 64
  type: CableApcExtension
  components:
  - pos: 2.5,3.5
    parent: 0
    type: Transform
- uid: 65
  type: CableApcExtension
  components:
  - pos: 2.5,4.5
    parent: 0
    type: Transform
- uid: 66
  type: CableApcExtension
  components:
  - pos: 1.5,0.5
    parent: 0
    type: Transform
- uid: 67
  type: SubstationWallBasic
  components:
  - pos: 0.5,3.5
    parent: 0
    type: Transform
- uid: 68
  type: GeneratorWallmountAPU
  components:
  - pos: 0.5,0.5
    parent: 0
    type: Transform
- uid: 69
  type: APCHighCapacity
  components:
  - rot: -1.5707963267948966 rad
    pos: 4.5,0.5
    parent: 0
    type: Transform
- uid: 70
  type: Poweredlight
  components:
  - rot: 1.5707963267948966 rad
    pos: 1.5,3.5
    parent: 0
    type: Transform
  - powerLoad: 0
    type: ApcPowerReceiver
- uid: 71
  type: Poweredlight
  components:
  - rot: -1.5707963267948966 rad
    pos: 3.5,3.5
    parent: 0
    type: Transform
  - powerLoad: 0
    type: ApcPowerReceiver
- uid: 72
  type: ChairPilotSeat
  components:
  - rot: 3.141592653589793 rad
    pos: 2.5,4.5
    parent: 0
    type: Transform
  - bodyType: Static
    type: Physics
...
