- type: entity
  parent: Clothing
  id: ClothingNeckBase
  abstract: true
  name: neck
  description:
  components:
  - type: Clothing
    size: 10
    QuickEquip: true
    Slots:
    - neck
  - type: Sprite
    state: icon
