- type: entity
  name: "item"
  id: BaseItem
  abstract: true
  components:
  - type: Item
    size: 5
  - type: Clickable
  - type: InteractionOutline
  - type: MovedByPressure
  - type: DamageOnHighSpeedImpact
  - type: CollisionWake
  - type: TileFrictionModifier
    modifier: 0.5
  - type: Physics
    bodyType: Dynamic
    fixedRotation: false
    fixtures:
    - shape:
        !type:PhysShapeAabb
          bounds: "-0.25,-0.25,0.25,0.25"
      mass: 5
      layer:
      - Clickable
      mask:
      - Impassable
      - VaultImpassable
      restitution: 0.3  # fite me
      friction: 0.2
  - type: Sprite
    drawdepth: Items
    noRot: false
  - type: Pullable
  - type: ExplosionLaunched
