- type: entity
  id: BaseNarsiStructure
  abstract: true
  components:
  - type: Anchorable
  - type: Transform
    anchored: true
    noRot: true
  - type: Clickable
  - type: InteractionOutline
  - type: NarsiCultStructure
  - type: Damageable
    damageContainer: Inorganic
    damageModifierSet: Metallic
  - type: Destructible
    thresholds:
    - trigger: !type:DamageTrigger
        damage: 500
      behaviors:
      - !type:DoActsBehavior
        acts: [ "Destruction" ]
    - trigger: !type:DamageTrigger
        damage: 25
      behaviors:
      - !type:PlaySoundBehavior
        sound:
          collection: MetalBreak
      - !type:DoActsBehavior
        acts: [ "Destruction" ]
