- type: job
  id: Bartender
  name: "bartender"
  positions: 1
  startingGear: BartenderGear
  departments:
  - Civilian
  icon: "Bartender"
  supervisors: "the head of personnel"
  access:
  - Service
  - Maintenance
  - Bar

- type: startingGear
  id: BartenderGear
  equipment:
    head: ClothingHeadHatTophat
    innerclothing: ClothingUniformJumpsuitBartender
    outerclothing: ClothingOuterVestKevlar
    backpack: ClothingBackpackFilled
    shoes: ClothingShoesColorBlack
    idcard: BartenderPDA
    ears: ClothingHeadsetService
  innerclothingskirt: ClothingUniformJumpskirtBartender
  satchel: ClothingBackpackSatchelFilled
  duffelbag: ClothingBackpackDuffelFilled
