- type: job
  id: Botanist
  name: "botanist"
  positions: 2
  spawnPositions: 2
  startingGear: BotanistGear
  departments:
  - Civilian
  icon: "Botanist"
  access:
  - Service
  - Hydroponics
  - Maintenance

- type: startingGear
  id: BotanistGear
  equipment:
    innerclothing: ClothingUniformJumpsuitHydroponics
    backpack: ClothingBackpackFilled
    shoes: ClothingShoesColorBrown
    idcard: BotanistPDA
    ears: ClothingHeadsetService
    outerclothing: ClothingOuterApronBotanist
