- type: job
  id: Botanist
  name: "botanist"
  startingGear: BotanistGear
  departments:
  - Civilian
  icon: "Botanist"
  supervisors: "the head of personnel"
  access:
  - Service
  - Maintenance
  - Hydroponics

- type: startingGear
  id: BotanistGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitHydroponics
    back: ClothingBackpackHydroponicsFilled
    shoes: ClothingShoesColorBrown
    id: BotanistPDA
    ears: ClothingHeadsetService
    outerclothing: ClothingOuterApronBotanist
  innerclothingskirt: ClothingUniformJumpskirtHydroponics
  satchel: ClothingBackpackSatchelHydroponicsFilled
  duffelbag: ClothingBackpackDuffelFilled
