- type: job
  id: Chaplain
  name: "chaplain"
  positions: 1
  startingGear: ChaplainGear
  department:
  - Civilian
  icon: "Chaplain"
  access:
  - Chapel
  - Maintenance

- type: startingGear
  id: ChaplainGear
  equipment:
    innerclothing: UniformChaplain
    backpack: BackpackClothing
    shoes: ShoesBlack
    idcard: ChaplainPDA
    ears: HeadsetService
