#- type: job
#  id: Chaplain
#  name: "chaplain"
#  positions: 1
#  startingGear: ChaplainGear
#  departments:
#  - Civilian
#  icon: "Chaplain"
#  access:
#  - Chapel
#  - Maintenance
#- type: startingGear
#  id: ChaplainGear
#  equipment:
#    innerclothing: ClothingUniformJumpsuitChaplain
#    backpack: ClothingBackpack
#    shoes: ClothingShoesColorBlack
#    idcard: ChaplainPDA
#    ears: ClothingHeadsetService
#  innerclothingskirt: ClothingUniformJumpskirtChaplain

