- type: job
  id: Chaplain
  name: "chaplain"
  startingGear: ChaplainGear
  departments:
  - Civilian
  icon: "Chaplain"
  supervisors: "the head of personnel"
  access:
  - Chapel
  - Maintenance

- type: startingGear
  id: ChaplainGear
  equipment:
    innerclothing: ClothingUniformJumpsuitChaplain
    backpack: ClothingBackpack
    shoes: ClothingShoesColorBlack
    idcard: ChaplainPDA
    ears: ClothingHeadsetService
  innerclothingskirt: ClothingUniformJumpskirtChaplain

