- type: job
  id: Chef
  name: "chef"
  positions: 1
  startingGear: ChefGear
  department:
  - Civilian
  icon: "Chef"
  access:
  - Service

- type: startingGear
  id: ChefGear
  equipment:
    innerclothing: UniformChef
    backpack: BackpackClothing
    shoes: ShoesBlack
    idcard: ChefPDA
