- type: job
  id: Chef
  name: "chef"
  startingGear: ChefGear
  departments:
  - Civilian
  icon: "Chef"
  supervisors: "the head of personnel"
  access:
  - Service
  - Maintenance

- type: startingGear
  id: ChefGear
  equipment:
    innerclothing: ClothingUniformJumpsuitChef
    head: ClothingHeadHatChef
    backpack: ClothingBackpackFilled
    shoes: ClothingShoesColorBlack
    idcard: ChefPDA
    ears: ClothingHeadsetService
    outerclothing: ClothingOuterApronChef
  innerclothingskirt: ClothingUniformJumpskirtChef
  satchel: ClothingBackpackSatchelFilled
  duffelbag: ClothingBackpackDuffelFilled
