- type: job
  id: Clown
  name: "clown"
  positions: 1
  startingGear: ClownGear
  departments:
  - Civilian
  icon: "Clown"
  access:
  - Theatre
  - Maintenance
  special: !type:ClownSpecial {}

- type: startingGear
  id: ClownGear
  equipment:
    innerclothing: ClothingUniformJumpsuitClown
    backpack: ClothingBackpackClownFilled
    shoes: ClothingShoesClown
    mask: ClothingMaskClown
    pocket1: BikeHorn
    idcard: ClownPDA
    ears: ClothingHeadsetService
