- type: job
  id: Clown
  name: "clown"
  positions: 1
  startingGear: ClownGear
  department:
  - Civilian
  icon: "Clown"
  access:
  - Theatre

- type: startingGear
  id: ClownGear
  equipment:
    innerclothing: UniformClown
    backpack: ClownPack
    shoes: ShoesClown
    mask: MaskClown
    pocket1: BikeHorn
    idcard: ClownPDA
