- type: job
  id: Janitor
  name: "janitor"
  positions: 1
  startingGear: JanitorGear
  departments:
  - Civilian
  icon: "Janitor"
  access:
  - Janitor
  - Maintenance

- type: startingGear
  id: JanitorGear
  equipment:
    innerclothing: ClothingUniformJumpsuitJanitor
    backpack: ClothingBackpackFilled
    shoes: ClothingShoesGaloshes
    head: ClothingHeadHatPurplesoft
    idcard: JanitorPDA
    ears: ClothingHeadsetService
    belt: ClothingBeltJanitorFilled
