- type: job
  id: Mime
  name: job-name-mime
  description: job-description-mime
  playTimeTracker: JobMime
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 14400 #4 hrs
  startingGear: MimeGear
  icon: "JobIconMime"
  supervisors: job-supervisors-hop
  access:
  - Theatre
  - Maintenance
  special:
  - !type:AddComponentSpecial
    components:
    - type: MimePowers

- type: startingGear
  id: MimeGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitMime
    back: ClothingBackpackMimeFilled
    head: ClothingHeadHatBeret
    belt: ClothingBeltSuspenders
    gloves: ClothingHandsGlovesLatex
    shoes: ClothingShoesColorWhite
    pocket1: CrayonMime
    pocket2: Paper
    mask: ClothingMaskMime
    id: MimePDA
    ears: ClothingHeadsetService
  innerclothingskirt: ClothingUniformJumpskirtMime
  satchel: ClothingBackpackSatchelMimeFilled
  duffelbag: ClothingBackpackDuffelMimeFilled

- type: entity
  id: ActionMimeInvisibleWall
  name: mime-invisible-wall
  description: mime-invisible-wall-desc
  noSpawn: true
  components:
  - type: InstantAction
    priority: -1
    useDelay: 30
    icon: Structures/Walls/solid.rsi/full.png
    event: !type:InvisibleWallActionEvent
