- type: job
  id: Musician
  name: "musician"
  startingGear: MusicianGear
  departments:
  - Civilian
  icon: "Musician"
  supervisors: "whoever hires you"
  access:
  - Maintenance # TODO Remove maint access for all gimmick jobs once access work is completed
  - Theatre
  special:
  - !type:GiveItemOnHolidaySpecial
    holiday: MikuDay
    prototype: BoxPerformer

- type: startingGear
  id: MusicianGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitLawyerPurple
    back: ClothingBackpackMusicianFilled
    eyes: ClothingEyesGlassesSunglasses
    shoes: ClothingShoesColorBlack
    id: MusicianPDA
    ears: ClothingHeadsetService
  satchel: ClothingBackpackSatchelMusicianFilled
  duffelbag: ClothingBackpackDuffelMusicianFilled
