- type: job
  id: ServiceWorker
  name: "service worker"
  startingGear: ServiceWorkerGear
  departments:
  - Civilian
  icon: "ServiceWorker"
  supervisors: "chefs, botanists, the bartender, and the head of personnel"
  canBeAntag: false
  access:
  - Service
  - Maintenance
  - Bar
  - Kitchen

- type: startingGear
  id: ServiceWorkerGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitBartender
    back: ClothingBackpackFilled
    shoes: ClothingShoesColorBlack
    id: ServiceWorkerPDA
    ears: ClothingHeadsetService
  innerclothingskirt: ClothingUniformJumpskirtBartender
  satchel: ClothingBackpackSatchelFilled
  duffelbag: ClothingBackpackDuffelFilled
