- type: entity
  id: BaseRatvarStructure
  parent: BaseStructure
  abstract: true
  components:
  - type: Transform
    anchored: true
    noRot: true
  - type: InteractionOutline
  - type: RatvarStructure
  - type: Damageable
    damageContainer: Inorganic
    damageModifierSet: Metallic
  - type: Destructible
    thresholds:
    - trigger: !type:DamageTrigger
        damage: 1000
      behaviors:
      - !type:DoActsBehavior
        acts: [ "Destruction" ]
    - trigger: !type:DamageTrigger
        damage: 25
      behaviors:
      - !type:PlaySoundBehavior
        sound:
          collection: MetalBreak
      - !type:SpawnEntitiesBehavior
        spawn:
          BrassPlasteel:
            min: 1
            max: 3
      - !type:DoActsBehavior
        acts: [ "Destruction" ]
