- type: entity
  abstract: true
  parent: BaseStructure
  id: WallBase
  name: basewall
  description: Keeps the air in and the greytide out.
  placement:
    mode: SnapgridCenter
    snap:
    - Wall
  components:
  - type: Tag
    tags:
    - Wall
  - type: Sprite
    netsync: false
    drawdepth: Walls
  - type: Icon
    state: full
  - type: Damageable
    damageContainer: Inorganic
    damageModifierSet: Metallic
  - type: Physics
    bodyType: Static
  - type: Fixtures
    fixtures:
    - shape:
        !type:PhysShapeAabb
          bounds: "-0.5,-0.5,0.5,0.5"
      layer:
      - Opaque
      - Impassable
      - MobImpassable
      - VaultImpassable
      - SmallImpassable
  - type: Occluder
    sizeX: 32
    sizeY: 32
  - type: Airtight
  - type: IconSmooth
    key: walls
    base: solid
