- type: job
  id: ResearchDirector
  name: "research director"
  head: true
  startingGear: ResearchDirectorGear
  departments:
  - Command
  - Science
  icon: "ResearchDirector"
  requireAdminNotify: true
  supervisors: "the captain"
  canBeAntag: false
  access:
  - Research
  - Command
  - Maintenance
  - ResearchDirector

- type: startingGear
  id: ResearchDirectorGear
  equipment:
    innerclothing: ClothingUniformJumpsuitResearchDirector
    backpack: ClothingBackpackScienceFilled
    shoes: ClothingShoesColorBrown
    outerclothing: ClothingOuterCoatLab
    idcard: RnDPDA
    ears: ClothingHeadsetScience
  innerclothingskirt: ClothingUniformJumpskirtResearchDirector
  satchel: ClothingBackpackSatchelScienceFilled
  duffelbag: ClothingBackpackDuffelScienceFilled
