- type: job
  id: ResearchDirector
  name: "research director"
  head: true
  positions: 1
  startingGear: ResearchDirectorGear
  department:
  - Command
  - Science
  icon: "ResearchDirector"
  access:
  - Research
  - Command
  - Maintenance

- type: startingGear
  id: ResearchDirectorGear
  equipment:
    innerclothing: UniformResearchDirector
    backpack: BackpackClothing
    shoes: ShoesBrown
    outerclothing: OuterclothingLabcoatgenopen
    idcard: RnDPDA
