- type: antag
  id: Nukeops
  name: "Nuclear Operative"
  antagonist: true
  setPreference: true
  objective: "Find the nuke disk and blow up the station."

- type: antag
  id: NukeopsCommander
  name: "Nuclear Operative Commander"
  antagonist: true
  setPreference: true
  objective: "Lead your team to the destruction of the station."
