- type: entity
  id: CrateServiceJanitorialSupplies
  name: janitorial supplies crate
  description: Fight back against dirt and grime with Nanotrasen's Janitorial Essentials(tm)! Contains three buckets, caution signs, and cleaner grenades. Also has a single mop, broom, spray cleaner, rag, and trash bag.
  parent: CratePlastic
  components:
  - type: StorageFill
    contents:
      - id: MopItem
        amount: 1
      - id: MopBucket
        amount: 1
      - id: Bucket
        amount: 3
      - id: WetFloorSign
        amount: 2
      - id: Soap
        amount: 1
      - id: SprayBottleSpaceCleaner
        amount: 2
      - id: TrashBag
        amount: 2

- type: entity
  id: CrateServiceReplacementLights
  name: replacement lights crate
  description: May the light of Aether shine upon this station! Or at least, the light of forty two light tubes and twenty one light bulbs.
  parent: CrateGenericSteel
  components:
  - type: StorageFill
    contents:
      - id: BoxLighttube
        amount: 1
      - id: BoxLightbulb
        amount: 1

- type: entity
  id: CrateServiceSmokeables
  name: smokeables crate
  description: "Tired of a quick death on the station? Order this crate and chain-smoke your way to a coughy demise!"
  parent: CrateGenericSteel
  components:
  - type: StorageFill
    contents:
      - id: CigCartonGreen
        prob: 0.50
        orGroup: CigCarton1
      - id: CigCartonRed
        orGroup: CigCarton1
      - id: CigCartonBlue
        prob: 0.50
        orGroup: CigCarton2
      - id: CigCartonBlack
        orGroup: CigCarton2
      - id: CigarGoldCase
        prob: 0.05
        orGroup: Cigars
      - id: CigarCase
        orGroup: Cigars
      - id: Matchbox
        amount: 2

- type: entity
  id: CrateServiceCustomSmokable
  name: DIY smokeables crate
  description: Want to get a little creative with what you use to destroy your lungs? Then this crate is for you! Has everything you need to roll your own Cigarettes.
  parent: CrateGenericSteel
  components:
  - type: StorageFill
    contents:
    - id: PackPaperRolling
    - id: CigaretteFilter
      amount: 8
    - id: GroundTobacco
      amount: 4
    - id: Matchbox

- type: entity
  id: CrateServiceBureaucracy
  name: bureaucracy crate
  description: Several stacks of paper and a few pens, what more can you ask for.
  parent: CrateGenericSteel
  components:
  - type: StorageFill
    contents:
    - id: Paper
      amount: 15
    - id: Pen
      amount: 2
