- type: entity
  id: LockerWardenFilled
  suffix: Filled
  parent: LockerWarden
  components:
  - type: StorageFill
    contents:
      - id: FlashlightSeclite
      - id: WeaponDisabler
        prob: 0.3
      - id: ClothingHeadHatWarden
      - id: ClothingHeadHatBeretWarden
      - id: ClothingBeltSecurityFilled
      - id: Flash
      - id: ClothingEyesGlassesSecurity
      - id: ClothingHeadsetAltSecurity
      - id: ClothingHandsGlovesCombat
      - id: ClothingShoesBootsJack
      - id: ClothingOuterCoatWarden
      - id: ClothingOuterWinterWarden
      - id: RubberStampWarden
      - id: DoorRemoteArmory
      - id: ClothingOuterHardsuitWarden
      - id: HoloprojectorSecurity

- type: entity
  id: LockerSecurityFilled
  suffix: Filled
  parent: LockerSecurity
  components:
  - type: StorageFill
    contents:
      - id: FlashlightSeclite
        prob: 0.8
      - id: ClothingUniformJumpsuitSecGrey
        prob: 0.3
      - id: ClothingHeadHelmetHelmet
      - id: ClothingOuterArmorBulletproof
      - id: ClothingBeltSecurityFilled
      - id: Flash
        prob: 0.5
      - id: ClothingEyesGlassesSecurity
      - id: ClothingHeadsetSecurity
      - id: ClothingHandsGlovesColorBlack
      - id: ClothingShoesBootsJack

- type: entity
  id: LockerBrigmedicFilled
  suffix: Brigmedic, Filled
  parent: LockerSecurity
  components:
  - type: StorageFill
    contents:
      - id: Flash
      - id: WeaponDisabler
      - id: ClothingOuterHardsuitBrigmed
      - id: EncryptionKeyMedical
      - id: BoxSterileMask
      - id: MedkitFilled
      - id: MedkitCombatFilled
        prob: 0.6
      - id: MedkitAdvancedFilled
        prob: 0.3
      - id: MedkitOxygenFilled
        prob: 0.3
      - id: MedkitBruteFilled
        prob: 0.3
      - id: MedkitToxinFilled
        prob: 0.3
      - id: MedkitBurnFilled
        prob: 0.7

- type: entity
  id: LockerDetectiveFilled
  suffix: Filled
  parent: LockerDetective
  components:
  - type: StorageFill
    contents:
      - id: ClothingHeadHatFedoraBrown
      - id: ClothingNeckTieDet
      - id: ClothingOuterVestDetective
      - id: ClothingOuterCoatDetective
      - id: FlashlightSeclite
      - id: ForensicScanner
      - id: BoxForensicPad
      - id: WeaponRevolverInspector
      - id: DrinkDetFlask
      - id: SpeedLoaderMagnum

- type: entity
  id: ClosetBombFilled
  parent: ClosetBomb
  suffix: Filled
  components:
  - type: StorageFill
    contents:
      - id: ClothingHeadHelmetBombSuit
      - id: ClothingOuterSuitBomb
      - id: ClothingMaskGas

- type: entity
  id: ShotgunSafeDisabler
  suffix: Disabler
  parent: ShotgunSafe
  components:
  - type: StorageFill
    contents:
      - id: WeaponDisabler
        amount: 5

- type: entity
  id: ShotgunSafePistolMK58
  suffix: MK58
  parent: ShotgunSafe
  components:
  - type: StorageFill
    contents:
      - id: WeaponPistolMk58
        amount: 4
      - id: MagazinePistol
        amount: 8

- type: entity
  id: ShotgunSafeRifleLecter
  suffix: Lecter
  parent: ShotgunSafe
  components:
  - type: StorageFill
    contents:
      - id: WeaponRifleLecter
        amount: 2
      - id: MagazineRifle
        amount: 4

- type: entity
  id: ShotgunSafeSubMachineGunVector
  suffix: Vector
  parent: ShotgunSafe
  components:
  - type: StorageFill
    contents:
      - id: WeaponSubMachineGunVector
        amount: 2
      - id: MagazineMagnumSubMachineGun
        amount: 4

- type: entity
  id: ShotgunSafeShotgunEnforcer
  suffix: Enforcer
  parent: ShotgunSafe
  components:
  - type: StorageFill
    contents:
      - id: WeaponShotgunEnforcer
        amount: 2
      - id: MagazineShotgun
        amount: 4

- type: entity
  id: ShotgunSafeShotgunKammerer
  suffix: Kammerer
  parent: ShotgunSafe
  components:
  - type: StorageFill
    contents:
      - id: WeaponShotgunKammerer
        amount: 2
      - id: MagazineShotgun
        amount: 4

- type: entity
  id: ShotgunSafeSubMachineGunWt550
  suffix: Wt550
  parent: ShotgunSafe
  components:
  - type: StorageFill
    contents:
      - id: WeaponSubMachineGunWt550
        amount: 2
      - id: MagazineMagnumSubMachineGun
        amount: 4

- type: entity
  id: ShotgunSafeLaserCarbine
  suffix: Laser Carbine
  parent: ShotgunSafe
  components:
  - type: StorageFill
    contents:
      - id: WeaponLaserCarbine
        amount: 3
