- type: entity
  id: LockerWardenFilled
  suffix: Filled
  parent: LockerWarden
  components:
  - type: StorageFill
    contents:
      - id: TaserGun
        prob: 0.3
      - id: ClothingHeadHatWarden
        prob: 1
      - id: ClothingHeadHatBeretWarden
        prob: 1
      - id: ClothingBeltSecurityFilled
        prob: 1
      - id: Flash
        prob: 1
      - id: ClothingEyesGlassesSecurity
        prob: 1
      - id: ClothingHeadsetAltSecurity
        prob: 1
      - id: ClothingHandsGlovesCombat
        prob: 1
      - id: ClothingShoesBootsJack
        prob: 1

- type: entity
  id: LockerSecurityFilled
  suffix: Filled
  parent: LockerSecurity
  components:
  - type: StorageFill
    contents:
      - id: ClothingUniformJumpsuitSecGrey
        prob: 0.3
      - id: ClothingHeadHelmetHelmet
        prob: 1
      - id: ClothingOuterArmorBulletproof
        prob: 1
      - id: ClothingBeltSecurityFilled
        prob: 1
      - id: Flash
        prob: 0.5
      - id: ClothingEyesGlassesSecurity
        prob: 1
      - id: ClothingHeadsetSecurity
        prob: 1
      - id: ClothingHandsGlovesColorBlack
        prob: 1
      - id: ClothingShoesBootsJack
        prob: 1

- type: entity
  id: LockerDetectiveFilled
  suffix: Filled
  parent: LockerDetective
  components:
  - type: StorageFill
    contents:
      - id: ClothingHeadHatFedoraBrown
        prob: 1
      - id: ClothingNeckTieDet
        prob: 1
      - id: ClothingOuterVestDetective
        prob: 1
      - id: ClothingOuterCoatDetective
        prob: 1


- type: entity
  id: LockerBombFilled
  parent: LockerBomb
  suffix: Filled
  components:
  - type: StorageFill
    contents:
      - id: ClothingHeadHelmetBombSuit
        prob: 1
      - id: ClothingOuterSuitBomb
        prob: 1
      - id: ClothingMaskGas
        prob: 1
