# TODO: Add descriptions (many)
# TODO BODY: Part damage
- type: entity
  id: BasePart
  parent: [ BaseItem, BaseSurgeryWoundable]
  name: "body part"
  abstract: true
  components:
  - type: Damageable
    damageContainer: Biological
  - type: BodyPart
  - type: SurgeryBodyPart
    species: universal
  - type: Gibbable
  - type: ContainerContainer
    containers:
      bodypart: !type:Container
        ents: []
  - type: StaticPrice
    price: 100

- type: entity
  id: BaseTorso
  name: "torso"
  parent: BasePart
  abstract: true
  components:
  - type: BodyPart
    partType: Torso
  - type: SurgeryBodyPart
    species: universal
  - type: SurgeryWoundablePart
    canBeDollTarget: false
  - type: StaticPrice
    price: 500

- type: entity
  id: BaseHead
  name: "head"
  parent: BasePart
  abstract: true
  components:
  - type: BodyPart
    partType: Head
    vital: true
  - type: SurgeryBodyPart
    species: universal
  - type: Input
    context: "ghost"
  - type: SurgeryWoundablePart
    maxDamage: 120
    canBeExplosionTarget: false
  - type: Tag
    tags:
    - Head
  - type: StaticPrice
    price: 700

- type: entity
  id: BaseLeftArm
  name: "left arm"
  parent: BasePart
  abstract: true
  components:
  - type: BodyPart
    partType: Arm
    symmetry: Left
  - type: SurgeryBodyPart
    species: universal
  - type: StaticPrice
    price: 400
  - type: Tag
    tags:
    - LArm

- type: entity
  id: BaseRightArm
  name: "right arm"
  parent: BasePart
  abstract: true
  components:
  - type: BodyPart
    partType: Arm
    symmetry: Right
  - type: SurgeryBodyPart
    species: universal
  - type: StaticPrice
    price: 400
  - type: Tag
    tags:
    - RArm

- type: entity
  id: BaseLeftHand
  name: "left hand"
  parent: BasePart
  abstract: true
  components:
  - type: BodyPart
    partType: Hand
    symmetry: Left
  - type: SurgeryBodyPart
    species: universal
  - type: StaticPrice
    price: 200

- type: entity
  id: BaseRightHand
  name: "right hand"
  parent: BasePart
  abstract: true
  components:
  - type: BodyPart
    partType: Hand
    symmetry: Right
  - type: SurgeryBodyPart
    species: universal
  - type: StaticPrice
    price: 200

- type: entity
  id: BaseLeftLeg
  name: "left leg"
  parent: BasePart
  abstract: true
  components:
  - type: BodyPart
    partType: Leg
    symmetry: Left
  - type: SurgeryBodyPart
    species: universal
  - type: MovementBodyPart
  - type: StaticPrice
    price: 450
  - type: Tag
    tags:
    - LLeg

- type: entity
  id: BaseRightLeg
  name: "right leg"
  parent: BasePart
  abstract: true
  components:
  - type: BodyPart
    partType: Leg
    symmetry: Right
  - type: SurgeryBodyPart
    species: universal
  - type: MovementBodyPart
  - type: StaticPrice
    price: 450
  - type: Tag
    tags:
    - RLeg

- type: entity
  id: BaseLeftFoot
  name: "left foot"
  parent: BasePart
  abstract: true
  components:
  - type: BodyPart
    partType: Foot
    symmetry: Left
  - type: SurgeryBodyPart
    species: universal
  - type: StaticPrice
    price: 300

- type: entity
  id: BaseRightFoot
  name: "right foot"
  parent: BasePart
  abstract: true
  components:
  - type: BodyPart
    partType: Foot
    symmetry: Right
  - type: SurgeryBodyPart
    species: universal
  - type: StaticPrice
    price: 300
