- type: accessLevel
  id: Bar

- type: accessLevel
  id: Kitchen

- type: accessLevel
  id: Hydroponics

- type: accessLevel
  id: Service

- type: accessLevel
  id: Janitor

- type: accessLevel
  id: Theatre
