- type: entity
  id: ParticleAcceleratorBase
  abstract: true
  placement:
    mode: SnapgridCenter
  components:
    - type: InteractionOutline
    - type: Anchorable
      snap: true
    - type: Physics
      mass: 25
      bodyType: Static
      fixtures:
      - shape:
          !type:PhysShapeAabb
            bounds: "-0.49,-0.49,0.49,0.49"
        mask:
        - Opaque
        - Impassable
        - MobImpassable
        - VaultImpassable
    - type: SnapGrid
      offset: Center
    - type: Pullable
    - type: Clickable
