name: No submodule update checker

on:
  workflow_dispatch:

jobs:
  this_aint_right:
    name: Submodule update in pr found
    runs-on: ubuntu-latest
    steps:
      - name: Fail
        run: exit 1
