name: Publish

concurrency:
  group: publish

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  check_changes:
    runs-on: ubuntu-latest

    name: Check latest commit
  
    outputs:
      should_run: ${{ steps.should_run.outputs.should_run }}
    steps:
      - uses: actions/checkout@v2
      - name: print latest_commit
        run: echo ${{ github.sha }}

      - id: should_run
        continue-on-error: true
        name: check latest commit is less than a day
        if: ${{ github.event_name == 'schedule' }}
        run: test -z $(git rev-list  --after="24 hours"  ${{ github.sha }}) && echo "::set-output name=should_run::false"

  build:
    needs: check_changes
    if: ${{ needs.check_changes.outputs.should_run != 'false' }}
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.100

    - name: Get Engine Tag
      run: |
        cd RobustToolbox
        git fetch --depth=1

    - name: Package all
      run: |
        Tools/package_server_build.py -p win-x64 linux-x64 osx-x64 linux-arm64
        Tools/package_client_build.py

    - name: Update Build Info
      run: Tools/gen_build_info.py

    - name: Shuffle files around
      run: |
        mkdir "release/${{ github.sha }}"
        mv release/*.zip "release/${{ github.sha }}"

    - name: Upload files to mothership
      uses: appleboy/scp-action@master
      with:
        host: 108.61.171.191
        username: deployer
        key: ${{ secrets.BUILDS_SSH_KEY }}
        source: "release/${{ github.sha }}"
        target: "/var/www/builds.station14.ru/syndicate/builds/"
        strip_components: 1

    - name: Update manifest JSON
      uses: appleboy/ssh-action@master
      with:
        host: 108.61.171.191
        username: deployer
        key: ${{ secrets.BUILDS_SSH_KEY }}
        script: node ~/scripts/push_to_manifest.js -fork syndicate -id ${{ github.sha }}
