name: RSI Validator

on: [pull_request]
jobs:
  validate_rsis:
    name: Validate RSIs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Parse files
        uses: space-wizards/json-schema-validator@v1.0.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          json_schema: .github/rsi-schema.json
          json_path_pattern: .*meta.json$
